name: "Continuous Integration"

on:
  push:
  pull_request:

env:
  MAVEN_ARGS: "--no-transfer-progress -Dstyle.color=always"

jobs:
  build:

    name: Compile project and run tests (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21, 24 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Fetch cached Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-deps

      - name: Compile project, run tests
        run: |
          mvn test package
